version: "2"

services:
  sonarqube:
    image: sonarqube:7.7-community
    ports:
      - "9001:9000"
      - "9092:9092"
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5431/$SONAR_POSTGRES_USER
      - sonar.jdbc.username=$SONAR_POSTGRES_USER
      - sonar.jdbc.password=$SONAR_POSTGRES_PASSWORD
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    restart: always
    depends_on:
        - db

  db:
    image: postgres:11.2-alpine
    ports:
      - "5431:5432"
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=$SONAR_POSTGRES_USER
      - POSTGRES_PASSWORD=$SONAR_POSTGRES_PASSWORD
    restart: always
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  postgresql:
  postgresql_data:
